database: antigravity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/antigravity?serverTimezone=Asia/Seoul
    username: root
    password:
  sql:
    init:
      mode: always
      open-in-view: false
      continue-on-error: true
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:/sql/data.sql
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
