database: hsqldb

# Database Settings
spring:
  datasource:
    url: devDatabaseUrl
    username: sa
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  logging:
    level:
      org:
        springframework.web: debug
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true